# Generated by Django 5.2 on 2025-05-20 23:04

import devices.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# IMPORT DES NOUVEAUX VALIDATEURS ICI
from devices.models import validate_imei_format, validate_imei_luhn


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # LIGNE CORRIGÉE : Remplacer [devices.models.validate_imei] par les nouveaux validateurs
                ('imei', models.CharField(help_text='Enter the 15-digit IMEI number of your device. Dial *#06# to find it.', max_length=15, unique=True, validators=[devices.models.validate_imei_format, devices.models.validate_imei_luhn], verbose_name='IMEI Number')),
                ('make', models.CharField(help_text='e.g., Samsung, Apple, Google', max_length=100, verbose_name='Make/Brand')),
                ('model_name', models.CharField(help_text='e.g., Galaxy S23, iPhone 15 Pro', max_length=100, verbose_name='Model Name')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('storage_capacity', models.CharField(help_text='e.g., 128GB, 256GB, 1TB', max_length=20, verbose_name='Storage Capacity')),
                ('distinguishing_features', models.TextField(blank=True, help_text='e.g., Carbon fiber case, small scratch on bottom right corner', null=True, verbose_name='Distinguishing Features')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('STOLEN', 'Reported Stolen'), ('RECOVERED', 'Recovered/Resolved'), ('FALSE_ALARM', 'False Alarm')], default='NORMAL', max_length=20, verbose_name='Status')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registered Device',
                'verbose_name_plural': 'Registered Devices',
                'ordering': ['-registration_date'],
            },
        ),
    ]