# Generated by Django 5.2 on 2025-05-21 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheftReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Case ID')),
                ('date_time_of_theft', models.DateTimeField(verbose_name='Date and Time of Theft')),
                ('is_time_approximate', models.BooleanField(default=True, verbose_name='Is Time Approximate?')),
                ('last_known_location', models.CharField(max_length=255, verbose_name='Last Known Location')),
                ('circumstances', models.TextField(verbose_name='Circumstances of Theft')),
                ('additional_details', models.TextField(blank=True, null=True, verbose_name='Additional Details')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='Reported At')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Report Last Updated')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Report'), ('OWNER_RECOVERED', 'Resolved - Recovered by Owner'), ('FINDER_RETURNED', 'Resolved - Returned by Finder'), ('RESOLVED_FALSE_ALARM', 'Resolved - False Alarm')], default='ACTIVE', max_length=30, verbose_name='Report Status')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theft_report', to='devices.registereddevice')),
            ],
            options={
                'verbose_name': 'Theft Report',
                'verbose_name_plural': 'Theft Reports',
                'ordering': ['-reported_at'],
            },
        ),
    ]
