# Generated by Django 5.2 on 2025-05-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_theftreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='theftreport',
            name='region_of_theft',
            field=models.CharField(choices=[('AD', 'Adamaoua'), ('CE', 'Center'), ('ES', 'East'), ('FN', 'Far North'), ('LT', 'Littoral'), ('NO', 'North'), ('NW', 'North-West'), ('OU', 'West'), ('SU', 'South'), ('SW', 'South-West'), ('UN', 'Unknown/Other')], default='UN', help_text='Select the region where the theft occurred.', max_length=2, verbose_name='Region of Theft'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theftreport',
            name='case_id',
            field=models.CharField(editable=False, max_length=30, unique=True, verbose_name='Case ID'),
        ),
    ]
