# Generated by Django 5.2 on 2025-05-22 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_foundreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundreport',
            name='matched_device_direct',
            field=models.ForeignKey(blank=True, help_text='Direct link to the registered device, if matched independently of a theft report.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_found_reports', to='devices.registereddevice'),
        ),
        migrations.AlterField(
            model_name='foundreport',
            name='theft_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='found_reports', to='devices.theftreport'),
        ),
    ]
